default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  database: <%= ENV["DATABASE_NAME"] %>
  port: <%= ENV["DATABASE_PORT"] %>
  host: <%= ENV["DATABASE_HOST"] %>


development:
  <<: *default
  database: gamelibrary_development

test:
  <<: *default
  database: gamelibrary_test

production:
  <<: *default
  database: gamelibrary_production
  username: gamelibrary
  password: <%= ENV['GAMELIBRARY_DATABASE_PASSWORD'] %>
