default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  timeout: 5000

development:
  <<: *default
  database: gamelibrary_development

test:
  <<: *default
  database: gamelibrary_test

production:
  <<: *default
  database: gamelibrary_production
  username: gamelibrary
  password: <%= ENV['GAMELIBRARY_DATABASE_PASSWORD'] %>
